// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoAWKePt0F5wB6KSZ_zy7GOOcphEkUmIw',
    appId: '1:326370310717:web:39e86f3770bb5f7715c854',
    messagingSenderId: '326370310717',
    projectId: 'qarzdaftarcha',
    authDomain: 'qarzdaftarcha.firebaseapp.com',
    storageBucket: 'qarzdaftarcha.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPU7DmlzXrTxtZX2ntk00JEWBJngyy73s',
    appId: '1:326370310717:android:b783c811410fb69a15c854',
    messagingSenderId: '326370310717',
    projectId: 'qarzdaftarcha',
    storageBucket: 'qarzdaftarcha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK33l2ZZn-SkLWJtlP4yyg23ZmbJBLiAI',
    appId: '1:326370310717:ios:fc964886a6d25bbe15c854',
    messagingSenderId: '326370310717',
    projectId: 'qarzdaftarcha',
    storageBucket: 'qarzdaftarcha.firebasestorage.app',
    iosBundleId: 'com.example.forfirebaseconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK33l2ZZn-SkLWJtlP4yyg23ZmbJBLiAI',
    appId: '1:326370310717:ios:fc964886a6d25bbe15c854',
    messagingSenderId: '326370310717',
    projectId: 'qarzdaftarcha',
    storageBucket: 'qarzdaftarcha.firebasestorage.app',
    iosBundleId: 'com.example.forfirebaseconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoAWKePt0F5wB6KSZ_zy7GOOcphEkUmIw',
    appId: '1:326370310717:web:a0128781f3e8d41a15c854',
    messagingSenderId: '326370310717',
    projectId: 'qarzdaftarcha',
    authDomain: 'qarzdaftarcha.firebaseapp.com',
    storageBucket: 'qarzdaftarcha.firebasestorage.app',
  );
}
